export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, sidebar, app, widgets }) {
  return (
    <div className="flex min-h-screen max-w-[1700px] mx-auto">
      {sidebar}
      {app}
      {widgets}
      {children}
    </div>
  );
}
