import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, sidebar, feed, widgets }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="flex min-h-screen max-w-7xl mx-auto">
          {sidebar}
          {feed}
          {widgets}
          {children}
        </div>
      </body>
    </html>
  );
}
